Repository TheClimeet/climeet-iOS, pull requests merged in 2025-01, with the labels that each got.

#27 DesignSystem 'TopBar' 에 underLine 추가
  Climeet-iOS/Climeet-iOS.xcodeproj/project.pbxproj
  Climeet-iOS/Climeet-iOS/Resources/Fonts/Font+.swift
  Climeet-iOS/Climeet-iOS/Resources/Fonts/FontTester.swift
  Climeet-iOS/Climeet-iOS/Resources/Fonts/Pretendard-Bold.ttf
  Climeet-iOS/Climeet-iOS/Resources/Fonts/Pretendard-Medium.ttf
  Climeet-iOS/Climeet-iOS/Resources/Fonts/Pretendard-Regular.ttf
  Climeet-iOS/Climeet-iOS/Resources/Fonts/Pretendard-SemiBold.ttf
  DesignSystem/Sources/DesignSystem/CommonUI/TopBar.swift
Labels: 고민 내용

#23 .run 이펙트 내부 에러 처리
  Climeet-iOS/Climeet-iOS/Presentation/Home/BestClimber/HomeBestClimberReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Home/HomeGymShortcut/HomeGymShortcutReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/RouteSelection/RouteSelectionReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Shorts/Shorts Reducers/ShortsDeckReducer/ShortsDeckReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Shorts/Shorts Reducers/UploadShorts/AddVideoTagReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Shorts/Shorts Reducers/UploadShorts/ShortsPostingReducer.swift
Labels: feature

#28 로그인/회원가입 (간편로그인, 닉네임설정, 프로필설정, 클라이밍레벨)
  Climeet-iOS/Climeet-iOS.xcodeproj/project.pbxproj
  Climeet-iOS/Climeet-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Climeet-iOS/Climeet-iOS/App/Climeet_iOSApp.swift
  Climeet-iOS/Climeet-iOS/Climeet-iOS.entitlements
  Climeet-iOS/Climeet-iOS/Common/Constant/Constant+.swift
  Climeet-iOS/Climeet-iOS/Common/Services/ValidateService.swift
  Climeet-iOS/Climeet-iOS/Data/Client/ClimberClient.swift
  Climeet-iOS/Climeet-iOS/Data/Client/KakaoClient.swift
  Climeet-iOS/Climeet-iOS/Data/Client/NaverClient.swift
  Climeet-iOS/Climeet-iOS/Data/Common/APIClient+Extension.swift
  Climeet-iOS/Climeet-iOS/Data/DTO/Kakao/KakaoDTO.swift
  Climeet-iOS/Climeet-iOS/Data/DTO/Naver/NaverDTO.swift
  Climeet-iOS/Climeet-iOS/Data/EndPoint/NaverEndPoint.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/AuthReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/AuthView.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/CheckLevel/CheckLevelReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/CheckLevel/CheckLevelView.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/SetNickname/SetNicknameReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/SetNickname/SetNicknameView.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/SetProfile/SetProfileReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/SetProfile/SetProfileView.swift
  Climeet-iOS/Climeet-iOS/Resources/Info.plist
  DesignSystem/Sources/DesignSystem/CommonUI/TooltipView.swift
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/AppleLogo.imageset/AppleLogo.svg
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/AppleLogo.imageset/Contents.json
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/AuthLogo.imageset/AuthLogo.svg
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/AuthLogo.imageset/Contents.json
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/AuthTooltipIcon.imageset/AuthTooltipIcon.svg
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/AuthTooltipIcon.imageset/Contents.json
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/KakaoLogo.imageset/Contents.json
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/KakaoLogo.imageset/KakaoLogo.svg
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/NaverLogo.imageset/Contents.json
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/NaverLogo.imageset/NaverLogo.svg
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/error_outline.imageset/Contents.json
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/error_outline.imageset/error_outline.svg
  NetworkKit/Sources/NetworkKit/Kit/APIClient.swift
  NetworkKit/Sources/NetworkKit/Kit/APIInterceptor.swift
  NetworkKit/Sources/NetworkKit/Kit/EndPoint.swift
Labels: feature

#32 feat: AuthSearchBar
  Climeet-iOS/Climeet-iOS/Resources/Assets.xcassets/Auth/highlight_off.imageset/Contents.json
  Climeet-iOS/Climeet-iOS/Resources/Assets.xcassets/Auth/highlight_off.imageset/highlight_off.svg
  DesignSystem/Sources/DesignSystem/CommonUI/SearchBar/AuthSearchBar.swift
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/highlight_off.imageset/Contents.json
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/Auth/highlight_off.imageset/highlight_off.svg
  DesignSystem/Sources/DesignSystem/Util/UIApplication.swift
Labels: feature, 고민 내용

#34 Feature/navigator
  Climeet-iOS/Climeet-iOS/App/Climeet_iOSApp.swift
  Climeet-iOS/Climeet-iOS/Data/Client/KakaoClient.swift
  Climeet-iOS/Climeet-iOS/Data/Common/SignupExtra.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/Auth/AuthReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/Auth/AuthView.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/AuthScreen.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/AuthScreenReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/CheckLevel/CheckLevelReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/CheckLevel/CheckLevelView.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/SetNickname/SetNicknameReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/SetNickname/SetNicknameView.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/SetProfile/SetProfileReducer.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/SetProfile/SetProfileView.swift
  Climeet-iOS/Climeet-iOS/Presentation/Root/RootScreen.swift
  Climeet-iOS/Climeet-iOS/Presentation/Root/RootScreenReducer.swift
Labels: feature, 고민 내용

#36 refactor: Toast Component
  Climeet-iOS/Climeet-iOS/App/Climeet_iOSApp.swift
  Climeet-iOS/Climeet-iOS/Presentation/Root/RootScreen.swift
  DesignSystem/Sources/DesignSystem/CommonUI/Toast.swift
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/check_circle_on_24.imageset/Contents.json
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/check_circle_on_24.imageset/check_circle_on_24.svg
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/ic_Info.imageset/Contents.json
  DesignSystem/Sources/DesignSystem/Resources/Icon.xcassets/ic_Info.imageset/ic_Info.svg
Labels: feature, 고민 내용

#37 Feature/set nickname tests
  Climeet-iOS/Climeet-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Climeet-iOS/Climeet-iOS/Data/Client/ClimberClient.swift
  Climeet-iOS/Climeet-iOS/Presentation/Auth/SetProfile/SetProfileReducer.swift
  Climeet-iOS/Climeet-iOSTests/AuthTests/CheckLevelTests.swift
  Climeet-iOS/Climeet-iOSTests/AuthTests/SetNicknameTests.swift
  Climeet-iOS/Climeet-iOSTests/AuthTests/SetProfileTests.swift
Labels: feature, 고민 내용
